# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    # command: --init-file /data/application/init.sql
    # volumes:
    #   - ./init.sql:/data/application/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
