services:
  api:
    ports:
      - ${APP_PORT}:${APP_PORT}
      - ${CLIENT_PORT}:${CLIENT_PORT}
    build:
      context: .
      dockerfile: ./apps/newsletter/Dockerfile
    environment:
      APP_PORT: ${APP_PORT}
      APP_HOST: ${APP_HOST}
      CLIENT_PORT: ${CLIENT_PORT}
      CLIENT_HOST: ${CLIENT_HOST}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

  db:
    image: postgres
    # restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./docker/initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
volumes:
  postgres_data:
