version: '3'

services:
  db:
    image: postgres
    # restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./docker/initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
volumes:
  postgres_data:
