export {
    FormatSize as TextIcon,
    PermMedia as MediaIcon,
    Assignment as TemplateIcon,
    // Cancel as CancelIcon,
    Clear as CancelIcon,
    ArrowForward as ArrowForwardIcon,
    Menu as MenuIcon,
    Close as CloseIcon,
    AccountCircle as AccountCircleIcon,
    Settings as SettingsIcon,
    Home as HomeIcon,
    ArrowBack as ArrowBackIcon,
    Edit as EditIcon,
    Add as AddIcon,
    Delete as DeleteIcon,
    CalendarToday as CalendarTodayIcon,
    CalendarMonth as CalendarMonthIcon,
    MoreVert as MoreVertIcon,
    LocationOn as LocationIcon
} from '@mui/icons-material';