app:
  host: localhost
  port: 3000
  sessionCookieName: newsletter_session
  sessionSecret: 123456789
db:
  host: localhost
  port: 5432
  name: newsletter
  username: postgres
  password: postgres

google:
  clientId: 123
  clientSecret: 123
  callbackUrl: localhost

gcs:
  bucketName: athena-newsletter

client:
  host: localhost
  port: 4200

systemAccount:
  email: idella.littel@ethereal.email
  password: eMseKrvEwJbwA4KXh9
  host: smtp.ethereal.email
  port: 587
