app:
  host: localhost
  port: 3000

db:
  host: localhost
  port: 5432
  name: newsletter
  username: postgres
  password: postgres

google:
  clientId: 123
  clientSecret: 123
  callbackUrl: localhost

gcs:
  bucketName: athena-newsletter

client:
  host: localhost
  port: 4200
