name: CI

on: [push]

# on:
#   push:
#     branches:
#       - main  # Only runs when changes are pushed to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Pulls the latest code from GitHub

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Change based on your project requirements

      - name: Install dependencies
        run: npm install # Change this based on your package manager (e.g., yarn install)

      - name: setup db
        run: npx nx run newsletter:db:init

      - name: Run tests
        run: jest -- newsletters.spec.ts

      - name: Stop and Clean Up
        run: npx nx run newsletter:db:destroy
